### ISSUE TITLE
[C#] Bad offset - system exception when accessing elements of a FixedTypeVector inside a map.

### ISSUE THREAD

**Issue by apranvoku** [mzaks/FlexBuffers-CSharp#1] opened 2020-02-06 16:17 UTC
The full error message is as follows:
Bad offset -System.Exception: Bad offset
  at FlexBuffers.FlxValue.ReadDouble (System.Byte[] bytes, System.Int32 offset, System.Byte width) [0x0001d] in FlxValue.cs:397 
  at FlexBuffers.FlxValue.get_AsDouble () [0x0000f] in FlxValue.cs:132 
  at CubeActiveMQ.ReloadData () [0x00081] in CubeActiveMQ.cs:77 
UnityEngine.Debug:Log(Object)
CubeActiveMQ:ReloadData() (at Assets/Scripts/CubeActiveMQ.cs:116)
CubeActiveMQ:Update() (at Assets/Scripts/CubeActiveMQ.cs:50)

I'm using Unity 2019.3.0f5 for this particular project. I was able to access a float that was the first value of the FlxValue.FromBytes(message.Content).AsMap structure. However, the next two values I need are part of a size 2 FixedTypeVector. They are floats, but can be accessed as double. When I try to access them like this, 
var flx = FlxValue.FromBytes(message.Content).AsMap;
var fuel_flow1 = flx["fuel_flow"][0].AsDouble;
var fuel_flow2 = flx["fuel_flow"][1].AsDouble;
Debug.Log("Fuel Flow 1 is " + fuel_flow1 );
Debug.Log("Fuel Flow 2 is " + fuel_flow2);

I recieved the above error. This works though:
var airspeed = flx["airspeed"].AsDouble;

Am I accessing it wrong? In the C++ Implementation, it works just fine. The .cs files I'm using are the latest available on this repo. 

Thanks!

**Comment by mzaks** [comment] 2020-02-06 16:46
@apranvoku could you please provide a binary file. I could then have a look and debug.
I assume the buffer was created with the C++ implementation?
Another easy way to get some info directly. Have a look what `flx.ToJson` returns and if it is what you would expect.

**Comment by apranvoku** [comment] 2020-02-06 17:00
I tried using flx.ToJson, and the following error message was generated: 
Bad offset -System.Exception: Bad offset
  at FlexBuffers.FlxValue.ReadDouble (System.Byte[] bytes, System.Int32 offset, System.Byte width) [0x0001d] in FlxValue.cs:397 
  at FlexBuffers.FlxValue.get_AsDouble () [0x0000f] in FlxValue.cs:132 
  at FlexBuffers.FlxValue.get_ToJson () [0x000bc] in FlxValue.cs:292 
  at FlexBuffers.FlxVector.get_ToJson () [0x00018] in FlxValue.cs:484 
  at FlexBuffers.FlxValue.get_ToJson () [0x000e8] in FlxValue.cs:297 
  at FlexBuffers.FlxMap.get_ToJson () [0x00026] in FlxValue.cs:599 
  at CubeActiveMQ.ReloadData () [0x00067] in CubeActiveMQ.cs:76 
UnityEngine.Debug:Log(Object)
CubeActiveMQ:ReloadData() (at Assets/Scripts/CubeActiveMQ.cs:117)
CubeActiveMQ:Start() (at Assets/Scripts/CubeActiveMQ.cs:40)

I'll provide the .cs code, but it uses a message from the Apache Artemis message broker, so I'm not sure how useful it'll be. Not sure if this is what you were looking for.
[CubeActiveMQ.txt](https://github.com/mzaks/FlexBuffers-CSharp/files/4166545/CubeActiveMQ.txt)

**Comment by phuongtran7** [comment] 2020-02-06 17:01
Hi,

I'm the one who send the buffer to @apranvoku. The buffers is a flexbuffers map that contains multiple values, include some vectors, creating using C++ implementation of Flexbuffers.

The vector that we are trying to access is a FixTypedVector of float values, the length of vector is 2. In debugging, I can see that the Flx can see the right length, however, whenever I tried accessing it it through the `bad offset` error.

I'll try and write the buffers into binary later. In the mean time, you can look at how I create the buffers in here: [https://github.com/phuongtran7/Ditto_ActiveMQ/blob/d9f0c5c4e281fe25fee28961d63b11694f59f8ed/Ditto_ActiveMQ/Datarefs.cpp#L29](https://github.com/phuongtran7/Ditto_ActiveMQ/blob/d9f0c5c4e281fe25fee28961d63b11694f59f8ed/Ditto_ActiveMQ/Datarefs.cpp#L29)

**Comment by mzaks** [comment] 2020-02-06 17:18
@phuongtran7 thank you for the pointer to the code, but it will take me a while to reproduce from that, it would be awesome if you could provide the binary file.

**Comment by phuongtran7** [comment] 2020-02-06 17:33
@mzaks,

The attached files are the binary of the buffer and a simple C++ application to test it. The output for the application should be:
```
Airspeed: 300.995
Fuel flow 0: 0.00506546
Fuel flow 1: 0
```

Thank you so much for your time and help.
[Test_Read_Flexbuffers_Binary.zip](https://github.com/mzaks/FlexBuffers-CSharp/files/4166750/Test_Read_Flexbuffers_Binary.zip)

**Comment by phuongtran7** [comment] 2020-02-06 18:04
I'm so sorry for the multiple replies. But below is a minimal example that I'm using to read the binary. It throw the same `bad offset` when accessing the `fuel_flow` vector inside the map.

```
    class Program
    {
        static void Main(string[] args)
        {
            byte[] body = File.ReadAllBytes("DittoOutput.bin");

            var flx = FlxValue.FromBytes(body).AsMap;
            Console.WriteLine($"True heading: {flx["true_heading"].AsDouble}");

            var ff = flx["fuel_flow"].AsVector;
            foreach (var value in ff)
            {
                Console.WriteLine($"Fuel flow : {value.AsDouble}");
            }
        }
    }
```

On a side note: the C++ program should label `Airspeed` as `True Heading`, but that's not impacting the application in anyway.

Thank you so much for your time and help.

**Comment by mzaks** [comment] 2020-02-06 18:04
Hm, that is an interesting one. At the line where exception is thrown `FlxValue.cs:397` it is thrown because of some sanity checks. One of them is that an offset is pointing into an aligned memory.
However it seems that this buffer is built with misaligned data. The exception is thrown for offset 363 where a 4 byte float needs to be read. Storing a 4 byte value starting at byte 363 is indeed a misaligned representation. So the buffer created with the C++ version is misaligned 🤷‍♂️.
@apranvoku for you to be able to read this buffer you would need to remove the alignment check at line, just replace the given line on `FlxValue:395` with following:
```
if (offset < 0 || bytes.Length <= (offset + width)) // || (offset & (width - 1)) != 0)
```
This will do the trick and you will be able to read the misaligned buffer in C#.

I will create an issue on the official FlatBuffers repo, so we can have a look and see if maybe I am mistaken and there is another problem, or there is need to be a fix in the C++ implementation of FlexBuffers.

Thanks for reporting and providing a buffer to reproduce.

**Comment by apranvoku** [comment] 2020-02-06 18:16
Changing FlxValue 395 fixed it for me. The Json was able to be generated correctly. Thanks! Shall I leave the issue up or close it?

**Comment by mzaks** [comment] 2020-02-06 18:17
I guess I can close it. 😀

**Closed as completed by mzaks** 2020-02-06 18:17 UTC
Labels: bug
